-- Migración EXACTA para arreglar las categorías de TODOS los APUs
-- Generado mapeando directamente la Columna A del Excel

UPDATE apu SET categoria_apu = 'CATEGORIA' WHERE REPLACE(nombre, ' ', '') = 'ITEM';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'MORTERO1:2';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'MORTERO1:3';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'MORTERO1:4';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'MORTERO1:5';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'MORT1:2IMP';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'MORT1:4IMP';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'CCTO1:2:2';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'CCTO1:2:3';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'CCTO1:2:4';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'CCTO1:3:6';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'CCTO1:4:8';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'CCTO1:2:2ACE';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'CCTO1:2:3ACE';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'CCTOCICLOPEO';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO1/4"';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO3/8"';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO1/2"';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO5/8"';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO3/4"';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO7/8"';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO1"';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO5mm.';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO6mm';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO8mm';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO9.5mm';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO10.5mm';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACERO12mm';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ACEROPROME';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'BLOQUE11X11';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'FORMALETA4u';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'BLOQUE2H';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'ANDAMIOS20u';
UPDATE apu SET categoria_apu = 'BASICOS' WHERE REPLACE(nombre, ' ', '') = 'LOSAPREFABR7CM';
UPDATE apu SET categoria_apu = 'PRELIMINARES' WHERE REPLACE(nombre, ' ', '') = 'CONTRTOPOG';
UPDATE apu SET categoria_apu = 'PRELIMINARES' WHERE REPLACE(nombre, ' ', '') = 'DESCAPOTEAMAQUINA';
UPDATE apu SET categoria_apu = 'PRELIMINARES' WHERE REPLACE(nombre, ' ', '') = 'DESCAPOTEAMANO';
UPDATE apu SET categoria_apu = 'CIMENTACIONES' WHERE REPLACE(nombre, ' ', '') = 'MEJORAMIENTPARACIMIENT';
UPDATE apu SET categoria_apu = 'CIMENTACIONES' WHERE REPLACE(nombre, ' ', '') = 'CIMIENCICLOP';
UPDATE apu SET categoria_apu = 'CIMENTACIONES' WHERE REPLACE(nombre, ' ', '') = 'CCTOZAPATAS';
UPDATE apu SET categoria_apu = 'CIMENTACIONES' WHERE REPLACE(nombre, ' ', '') = 'SOBRECIMLADE=20CM';
UPDATE apu SET categoria_apu = 'CIMENTACIONES' WHERE REPLACE(nombre, ' ', '') = 'SOBRECIMLADE=25CM';
UPDATE apu SET categoria_apu = 'CIMENTACIONES' WHERE REPLACE(nombre, ' ', '') = 'SOBRECBLOQMACIZE=30CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'CCTOVIGACIM27X27CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'CCTOVIGACIM40x40CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'VIGUETACIMEN15X20CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'CCTOCOLUMNA27X27CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'CCTOCOLUMNA40X40CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'COLUMNETA15X20CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'CCTOVIGAAER27X27CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'CCTOVIGAAER40x40CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'VIGUETA15X20CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'CCTOVCANAL30X25CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'CCTOVCANAL40x30CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'VIGADINTEL12X10CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS MADERA' WHERE REPLACE(nombre, ' ', '') = 'ESTRMADERA7X15CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS MADERA' WHERE REPLACE(nombre, ' ', '') = 'ESTRMADERA5x11CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'GRADAS90CMHUELLA27CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'ALFAJIA20CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'CCTOLOSAMACIZA12CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'CCTOLOSAMACIZA20CM';
UPDATE apu SET categoria_apu = 'ESTRUCTURAS CONCRETO' WHERE REPLACE(nombre, ' ', '') = 'LOSAPREINPAL';
UPDATE apu SET categoria_apu = 'FUNDICION DE PISO' WHERE REPLACE(nombre, ' ', '') = 'PISOPRIMARIOE=10CM';
UPDATE apu SET categoria_apu = 'FUNDICION DE PISO' WHERE REPLACE(nombre, ' ', '') = 'PISOPRIMARIOE=7CM';
UPDATE apu SET categoria_apu = 'MUROS' WHERE REPLACE(nombre, ' ', '') = 'MUROSOGACUADRILONGO';
UPDATE apu SET categoria_apu = 'MUROS' WHERE REPLACE(nombre, ' ', '') = 'MUROSOGAADOBON';
UPDATE apu SET categoria_apu = 'MUROS' WHERE REPLACE(nombre, ' ', '') = 'MUROTIZONCUADRILONGO';
UPDATE apu SET categoria_apu = 'MUROS' WHERE REPLACE(nombre, ' ', '') = 'MUROTIZONADOBON';
UPDATE apu SET categoria_apu = 'MUROS' WHERE REPLACE(nombre, ' ', '') = 'MUROPAPELILLOCUADRILONGO';
UPDATE apu SET categoria_apu = 'MUROS' WHERE REPLACE(nombre, ' ', '') = 'MUROSOGABLOQUEMACIZ';
UPDATE apu SET categoria_apu = 'MUROS' WHERE REPLACE(nombre, ' ', '') = 'MUROSOGABLOQUEHUECO';
UPDATE apu SET categoria_apu = 'CUBIERTAS' WHERE REPLACE(nombre, ' ', '') = 'TEJAACNo4';
UPDATE apu SET categoria_apu = 'CUBIERTAS' WHERE REPLACE(nombre, ' ', '') = 'TEJAACNo5';
UPDATE apu SET categoria_apu = 'CUBIERTAS' WHERE REPLACE(nombre, ' ', '') = 'TEJAACNo6';
UPDATE apu SET categoria_apu = 'CUBIERTAS' WHERE REPLACE(nombre, ' ', '') = 'TEJAACNo8';
UPDATE apu SET categoria_apu = 'CUBIERTAS' WHERE REPLACE(nombre, ' ', '') = 'TEJAACNo10';
UPDATE apu SET categoria_apu = 'CUBIERTAS' WHERE REPLACE(nombre, ' ', '') = 'CABALLETFIJO';
UPDATE apu SET categoria_apu = 'CUBIERTAS' WHERE REPLACE(nombre, ' ', '') = 'CLARABOYA4';
UPDATE apu SET categoria_apu = 'CUBIERTAS' WHERE REPLACE(nombre, ' ', '') = 'CLARABOYA6';
UPDATE apu SET categoria_apu = 'CUBIERTAS' WHERE REPLACE(nombre, ' ', '') = 'TVENTILANo4';
UPDATE apu SET categoria_apu = 'CUBIERTAS' WHERE REPLACE(nombre, ' ', '') = 'TVENTILANo6';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'CANALPVC';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'BAJANTEPVC';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGCEM8"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGCEM6"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGCEM4"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'CODOCEM4"';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGGRESS8"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGGRESS6"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGGRESS4"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'CODOGRESS4"';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGPVC8"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGPVC6"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGPVC4"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGPVC3"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGPVC2"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'AGLLUVPVC4"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'AGLLUVPVC3"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'AGLLUVPVC2"ENTIERRA';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'TEEPVCSAN6';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'TEEPVCSAN4';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'TEEPVCSAN3';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'TEEPVCSAN2';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'CODPVCSAN6';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'CODPVCSAN4';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'CODPVCSAN3';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'CODPVCSAN2';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'SIFONPVC2"';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'REJILLALUMI2';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'REJILLALUMI3';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'VALVPOZUE2"';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'VALVPOZUE3"';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGPVC4"ENTREPISOS';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGPVC3"ENTREPISOS';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'DESAGPVC2"ENTREPISOS';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'AGLLUVPVC4"ENTREPISOS';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'AGLLUVPVC3"ENTREPISOS';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'CAJINSP40X40H=40cm';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'CAJINSP60x60H=60cm';
UPDATE apu SET categoria_apu = 'CANALES Y BAJANTES' WHERE REPLACE(nombre, ' ', '') = 'CAJINSP80x80H=80cm';
UPDATE apu SET categoria_apu = 'PUNTOS SANITARIOS' WHERE REPLACE(nombre, ' ', '') = 'PuntoSANITARIOPVC4"terminado';
UPDATE apu SET categoria_apu = 'PUNTOS SANITARIOS' WHERE REPLACE(nombre, ' ', '') = 'PuntoSANITARIOPVC3"terminado';
UPDATE apu SET categoria_apu = 'PUNTOS SANITARIOS' WHERE REPLACE(nombre, ' ', '') = 'PuntoSANITARIOPVC2"terminado';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'INSTALACHCAPVCPRES1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'INSTALACHCAPVCPRES3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'INSTALACHCAPVCPRES1"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'TEEPRES1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'TEEPRES3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'CODOPRES1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'CODOPRES3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'ARM1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'ARM3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'ARH1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'ARH3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'REGISTRO1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'REGISTRO3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'LLAVEPD1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'PUNTOHCOPVC1/2"TERMINADO';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'LLAVEPD3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'LLAVBOLA1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'LLAVBOLA3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'CHEQUE1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'CHEQUE3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'GRIFO1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'NIPLEHG1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'NIPLEHG3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'CODOHG1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'CODOHG3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES HIDRAULICAS' WHERE REPLACE(nombre, ' ', '') = 'PTOHCOCPVC1/2"TERMINADO';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'DUCTOELECTRPVC1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'DUCTOELECTRPVC3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'DUCTOELECTRPVC1"';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'DUCTOELECTRCONDMET1/2"';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'DUCTOELECTRCONDMET3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'DUCTOELECTRCONDMET1"';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CAJILLAGALVA2X4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CAJILLAGALVAOCTOGON4X4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CAJILLAGALVATOMAESPEC';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'TOMACORRENSENCILLO';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'TOMACORRENDOBLE';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'TOMACORRENESPECIALtripol';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'INTERRUPTORSENCILLO';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'INTERRUPTOR';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'PLAFONPORCE';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CAJCONTADOR';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'TABLCONTROL';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'DUCTOACOMEMETAL3/4"4mt';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'DUCTOACOMEMETAL1"4mt';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CABLEADOENALUMINIOcal6';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CABLEADOENCOBREcal6';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CABLEADOENCOBREcal8';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CABLEADOENCOBREcal10';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CABLEADOENCOBREcal12';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'PTOELECTRICO110VTERMINADO';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'PAVBALDOSA';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'GUARDAESCOBBALDOSA';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'REVCER20x20pegacorconcolor';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'REVCER30x30pegacorconcolor';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'REVCER40x40pegacorconcolor';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'PAVCER20x20pegacorconcolor';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'PAVCER30x30pegacorconcolor';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'PAVCER40x40pegacorconcolor';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'GUARDCERAMH=10cmpegacorconcolor';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'REVCER20x20pegatradicional';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'REVCER30x30pegatradicional';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'REVCER40x40pegatradicional';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'PAVCER20x20pegatradicional';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'PAVCER30x30pegatradicional';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'PAVCER40x40pegatradicional';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'GUARDCERAMH=10cmpegatradicional';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'GUARDAESCOBMADERA';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'WINGALUMINIO';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'WINGPLASTICO';
UPDATE apu SET categoria_apu = 'ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'PISOVINILO';
UPDATE apu SET categoria_apu = 'REVOQUES' WHERE REPLACE(nombre, ' ', '') = 'REVRUSTICOENMUROS';
UPDATE apu SET categoria_apu = 'REVOQUES' WHERE REPLACE(nombre, ' ', '') = 'REVREFINADOENMUROS';
UPDATE apu SET categoria_apu = 'REVOQUES' WHERE REPLACE(nombre, ' ', '') = 'REVAFINACALENMUROS';
UPDATE apu SET categoria_apu = 'REVOQUES' WHERE REPLACE(nombre, ' ', '') = 'REVRUSTICOENPISOS';
UPDATE apu SET categoria_apu = 'REVOQUES' WHERE REPLACE(nombre, ' ', '') = 'REVREFINADOENPISOS';
UPDATE apu SET categoria_apu = 'REVOQUES' WHERE REPLACE(nombre, ' ', '') = 'FILOSYREMAT';
UPDATE apu SET categoria_apu = 'REVOQUES' WHERE REPLACE(nombre, ' ', '') = 'DILATACIONES';
UPDATE apu SET categoria_apu = 'REVOQUES' WHERE REPLACE(nombre, ' ', '') = 'PERLAPLATACH';
UPDATE apu SET categoria_apu = 'REVOQUES' WHERE REPLACE(nombre, ' ', '') = 'PERLARUSTICA';
UPDATE apu SET categoria_apu = 'PINTURAS DETALLADAS' WHERE REPLACE(nombre, ' ', '') = 'IMPRIMVINILORODILLO2manos';
UPDATE apu SET categoria_apu = 'PINTURAS DETALLADAS' WHERE REPLACE(nombre, ' ', '') = 'IMPRIMCOLBRODILLO2manos';
UPDATE apu SET categoria_apu = 'PINTURAS DETALLADAS' WHERE REPLACE(nombre, ' ', '') = 'PINTVINILOEXTRODILLO2manos';
UPDATE apu SET categoria_apu = 'PINTURAS DETALLADAS' WHERE REPLACE(nombre, ' ', '') = 'PINTVINILOEXTBROCHA2manos';
UPDATE apu SET categoria_apu = 'PINTURAS DETALLADAS' WHERE REPLACE(nombre, ' ', '') = 'PINTESMALTEVENTANAS2m';
UPDATE apu SET categoria_apu = 'PINTURAS DETALLADAS' WHERE REPLACE(nombre, ' ', '') = 'PINTESMALTERejasantep2man';
UPDATE apu SET categoria_apu = 'PINTURAS DETALLADAS' WHERE REPLACE(nombre, ' ', '') = 'PINTESMALTEPUERTAS2man';
UPDATE apu SET categoria_apu = 'PINTURAS DETALLADAS' WHERE REPLACE(nombre, ' ', '') = 'PINTENLACASOPLETE2man';
UPDATE apu SET categoria_apu = 'ESTUCOS' WHERE REPLACE(nombre, ' ', '') = 'ESTUCTRADIC';
UPDATE apu SET categoria_apu = 'ESTUCOS' WHERE REPLACE(nombre, ' ', '') = 'ESTUCPROFES';
UPDATE apu SET categoria_apu = 'CARPINTERIA METALICA' WHERE REPLACE(nombre, ' ', '') = 'PTALAMINACAL180.90X2.10mt';
UPDATE apu SET categoria_apu = 'CARPINTERIA METALICA' WHERE REPLACE(nombre, ' ', '') = 'PTALAMINACAL181.00X2.10mt';
UPDATE apu SET categoria_apu = 'CARPINTERIA METALICA' WHERE REPLACE(nombre, ' ', '') = 'PTALAMINACAL1.20X2.10,2hoj';
UPDATE apu SET categoria_apu = 'CARPINTERIA MADERA' WHERE REPLACE(nombre, ' ', '') = 'PTAENTAMBO0.70X2.10MT';
UPDATE apu SET categoria_apu = 'CARPINTERIA MADERA' WHERE REPLACE(nombre, ' ', '') = 'PTAENTAMBO0.80X2.10MT';
UPDATE apu SET categoria_apu = 'CARPINTERIA MADERA' WHERE REPLACE(nombre, ' ', '') = 'PTAENTAMBO0.90X2.10MT';
UPDATE apu SET categoria_apu = 'VENTANERIA' WHERE REPLACE(nombre, ' ', '') = 'VENTANALAMCAL22sinantep';
UPDATE apu SET categoria_apu = 'VENTANERIA' WHERE REPLACE(nombre, ' ', '') = 'VENTANALAMCAL22conantep';
UPDATE apu SET categoria_apu = 'VENTANERIA' WHERE REPLACE(nombre, ' ', '') = 'VIDRIOS3MM';
UPDATE apu SET categoria_apu = 'VENTANERIA' WHERE REPLACE(nombre, ' ', '') = 'VIDRIOS4MM';
UPDATE apu SET categoria_apu = 'VENTANERIA' WHERE REPLACE(nombre, ' ', '') = 'VIDRIOS5MM';
UPDATE apu SET categoria_apu = 'OBRA EXTERIORES' WHERE REPLACE(nombre, ' ', '') = 'SIKAESTUCO';
UPDATE apu SET categoria_apu = 'OBRA EXTERIORES' WHERE REPLACE(nombre, ' ', '') = 'ANDEN60CME=10CM';
UPDATE apu SET categoria_apu = 'OBRA EXTERIORES' WHERE REPLACE(nombre, ' ', '') = 'ANDEN90CME=10CM';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'SARDINELvehic12-18x50cm';
UPDATE apu SET categoria_apu = 'OBRA EXTERIORES' WHERE REPLACE(nombre, ' ', '') = 'EMPRADIZdirec';
UPDATE apu SET categoria_apu = 'OBRA EXTERIORES' WHERE REPLACE(nombre, ' ', '') = 'TERRACEO';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'CORTESVIAS';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'RELLENOVIAS';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'RETIROSOBRACargueretroexc';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'RETIROSOBRAAmano';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'SUB-BASE';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'PAVIMCCTOE=12cm';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'PAVIMCCTOE=15cm';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'PAVIMCCTOE=20cm';
UPDATE apu SET categoria_apu = 'ALCANTARILLADOS' WHERE REPLACE(nombre, ' ', '') = 'ALCANTARILLTUBCEM10"';
UPDATE apu SET categoria_apu = 'ALCANTARILLADOS' WHERE REPLACE(nombre, ' ', '') = 'ALCANTARILLTUBCEM12"';
UPDATE apu SET categoria_apu = 'ALCANTARILLADOS' WHERE REPLACE(nombre, ' ', '') = 'SUMIDEROA.LL';
UPDATE apu SET categoria_apu = 'ALCANTARILLADOS' WHERE REPLACE(nombre, ' ', '') = 'BASE+CAÑUELACAM.INSPECC';
UPDATE apu SET categoria_apu = 'ALCANTARILLADOS' WHERE REPLACE(nombre, ' ', '') = 'ANILLOCAMARINSPECCION';
UPDATE apu SET categoria_apu = 'ALCANTARILLADOS' WHERE REPLACE(nombre, ' ', '') = 'TAPA+BASESCAMINSPECCH>1.80mt';
UPDATE apu SET categoria_apu = 'ALCANTARILLADOS' WHERE REPLACE(nombre, ' ', '') = 'TAPA+BASESCAMINSPECCH<=1.80mt';
UPDATE apu SET categoria_apu = 'MOVIMIENTO DE TIERRA' WHERE REPLACE(nombre, ' ', '') = 'EXCMECANICAchambasCargueyretiro';
UPDATE apu SET categoria_apu = 'MOVIMIENTO DE TIERRA' WHERE REPLACE(nombre, ' ', '') = 'EXPLANACIONYEXTENDIDO';
UPDATE apu SET categoria_apu = 'MOVIMIENTO DE TIERRA' WHERE REPLACE(nombre, ' ', '') = 'EXPLANACIONYRETIRO';
UPDATE apu SET categoria_apu = 'MOVIMIENTO DE TIERRA' WHERE REPLACE(nombre, ' ', '') = 'RELLENOCOMPMaterialdelsitio90%ProctorM';
UPDATE apu SET categoria_apu = 'MOVIMIENTO DE TIERRA' WHERE REPLACE(nombre, ' ', '') = 'COMF,COMPACSUBRASANTE90%ProctorM';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'SUBBASE';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'BASEgranular';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'AC5/8"transfer';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'PAVCONCRETO18CM(V0-V2)Csuelo=4Kg/cm2';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'PAVCONCRETO20CM(V3-V8)Csuelo=4Kg/cm2';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'SEPARADOR';
UPDATE apu SET categoria_apu = 'VIAS' WHERE REPLACE(nombre, ' ', '') = 'ZONAVERDEMasde1000M2';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CAPACETE3/4"';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CAPACETE1"';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'BOTONTIMBRELuminex';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'CAMPTIMBRELuminex';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'SALIDAELECTREINTERRsencilloTodocostoLongprom4.50m';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'SALIDAELECTREINTERRdobleTodocostoLongprom4.50m';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'SALIDAELECTREINTERRconmutTodocostoLongprom4.50m';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'SALIDAELECTRYTOMACsencillTodocostoLongprom4.50m';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'SALIDAELECTRYTOMACdobleTodocostoLongprom4.50m';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'SALIDAELECTRYTOMAestufaTodocostoLongprom4.50m';
UPDATE apu SET categoria_apu = 'INSTALACIONES ELECTRICAS' WHERE REPLACE(nombre, ' ', '') = 'SALIDAELECTRYPLAFONporceTodocostoLongprom4.50m';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'BALDOSgranitoDUROTECH30.5X30.5cm';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'TABLONGRESSALFAGRESS30X30CM';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'TABLONGRESSALFAGRESS25X25CM';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'TABLONGRESSALFAGRESS20X10CM';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'DILATACIONENBRONCEsinm.o.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GRANITONo1PULIDO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GRANITONo2PULIDO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GRANITONo3PULIDO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GRANITONo1LAVADO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GRANITONo2LAVADO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GRANITONo3LAVADO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GRAVILLAlavadaNumero1';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GRAVILLAlavadaNumero2';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GRAVILLAlavadaNumero3';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GRAVILLAlavadaNumero4';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GUARDAESCOBGRAVILLALAVRectaH=10cm';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCconcenefGRAVILLALAVM/caña10x10cm';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GUARDAESCOBGRANITOpulidoRectaH=10cm';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCconcenefaGRANITOpulidoM/Caña10x10cm';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'GUARDAESCOBGRANITOlavadoRectaH=10cm';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCconcenefaGRANITOlavadoM/Caña10x10cm';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PELDAÑOgradaGRANITPULIDO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLNEGROCARACOL';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLGRISPUTUMAYO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLROSAHUILA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLtravertVILLADELEIVA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLGRISPERLA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLROSATACUEYO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLGRISRIOCLARO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLMULATACAMPIÑA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLVERDEANDES';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLTRAVERTINOPERUANO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLCAFÉPINTO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'MARMOLCREMAMARFIL';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITOGHIANDONE';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITOGIALLOSNFCO.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITOVerdeUBATUBA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITORojoGUAYANA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITOROSSAPORRINO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITOJASPE';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITONegroabsoluto';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITOLabradorClaro';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITOLabradorOscuro';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITOCaféBALTICO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITOGrisGUAYANA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PLACAGRANITOSIERRACHICA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PULIDOFINALGranitoomarmolEncerado';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PIEDRACORALINA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PIEDRAMUÑECA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PIEDRABLANCA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'PIEDRABOGOTANA';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'BALDOSgranitoMELATO33X33cm';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTBOTTICCINO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTMarmolGRIS';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTMarmolNEGRO';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTTRAVERTINO.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTVERDEANDES.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTGHIANDONE.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTROSSAPORRINO.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTVERDEUBATUBA.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTLABR.CLARO.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTLABROSCURO.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTJASPE.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTCAFÉBALTICO.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'G/ESCOBAS0,10MTGRISGUAYANA.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'ESPACATTOBLANCOHUILA.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'ESPACATTONegroCARACOL.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'ESPACATTOTRAVERTINO.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'ESPACATTOGRISHUILA.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'ESPACATTOBEIGEHUILA.';
UPDATE apu SET categoria_apu = 'ACABADOS' WHERE REPLACE(nombre, ' ', '') = 'ESPACATTOPiedraMUÑECA.';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER30x30Piso';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER25x25Piso';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER30,5x30,5Piso';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER20x25Pared';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER33x33Piso';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER30x40Pared';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER11x22Piso';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER35x35Piso';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER40x40Piso';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER20.5x20,5Piso';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER20.5x25Pared';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER20,5x30Pared';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER50x50Piso';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER55x55Piso';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'ENCHCER60x60Piso';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'TABLETA20x10pegatradicional';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'TABLETA10x10pegatradicional';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'TABLON25x25pegatradicional';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'TABLON33x33pegatradicional';
UPDATE apu SET categoria_apu = 'ENCHAPES CERAMICOS' WHERE REPLACE(nombre, ' ', '') = 'TABLONROJORomana15x15';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'GABINETEBAÑO';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'INCRUSTACIONESAcuacer';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'INCRUSTACIONESRoyal';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'INCRUSTACIONESStilo';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'INCRUSTACIONESNova';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'REMATESREDONDPorcelana';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'REMATESREDONDTraciametalica';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'TUBOCORTINADUCHA';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'ANTICORROSIVAS/Laminalineal';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'ANTICORROSIVAS/Laminallena';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'ESMALTES/Laminalineal';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'ESMALTES/Laminallena';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'ESMALTES/Maderalineal';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'ESMALTES/Maderallena';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'ESMALTES/Marcoslamina';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'ESMALTES/Marcosmadera';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'ESMALTES/Mueblesmadera';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'BARNIZS/Mueblesmadera';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'BARNIZPISOSMadera';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'TINTILLAS/Maderalineal';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'TINTILLAS/Maderallena';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'TINTILLAS/Muebles';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'CARBUROSOBREREPELLO';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'VINILOS/REPELLO2MANOS';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'VINILOS/RUSTICO2MANOS';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'VINILOS/ESTUCO2MANOS';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'LINEASTRAFICOA=0.10mt';
UPDATE apu SET categoria_apu = 'ACCESORIOS PARA ENCHAPES' WHERE REPLACE(nombre, ' ', '') = 'WASHPRIMERS/Metal';
UPDATE apu SET categoria_apu = 'ESTUCO Y PINTURA' WHERE REPLACE(nombre, ' ', '') = 'ESTUCO';
UPDATE apu SET categoria_apu = 'ESTUCO Y PINTURA' WHERE REPLACE(nombre, ' ', '') = 'ESTUCOYVINILO3manos';
UPDATE apu SET categoria_apu = 'ESTUCO Y PINTURA' WHERE REPLACE(nombre, ' ', '') = 'FILOSYDILATACIONES';
UPDATE apu SET categoria_apu = 'ESTUCO Y PINTURA' WHERE REPLACE(nombre, ' ', '') = 'ESTUCOSOBREMUROEXTERIOR';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'PRESERVADOPORINYECCION';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'GUADUAPRESERVADAPORINMERSION(Inmersión=24horas)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN ROLLIZA' WHERE REPLACE(nombre, ' ', '') = 'ROLLIZAEUCALIPTOPRESERVPORINMERSION(Inmersión=24horas)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'COLUMNAENGUADUAD=10CMIncluyeanclaje(Ltipo=3,40mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'COLUMNAENGUADUAD=12CMIncluyeanclaje(Ltipo=3,40mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'COLUMNAENGUADUAD=14CMIncluyeanclaje(Ltipo=3,40mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'COLUMNAENGUADUAD=16CMIncluyeanclaje(Ltipo=3,40mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'COLUMNAENGUADUAD=18CMIncluyeanclaje(Ltipo=3,40mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN ROLLIZA' WHERE REPLACE(nombre, ' ', '') = 'COLUMNAENROLLIZAD=10CMSinanclaje(Ltipo=3,40mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN ROLLIZA' WHERE REPLACE(nombre, ' ', '') = 'COLUMNAENROLLIZAD=12CMSinanclaje';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN ROLLIZA' WHERE REPLACE(nombre, ' ', '') = 'COLUMNAENROLLIZAD=14CMSinanclaje(Ltipo=3,40mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN ROLLIZA' WHERE REPLACE(nombre, ' ', '') = 'COLUMNAENROLLIZAD=16CMSinanclajeCOLUMNAENROLLIZAD=16CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN ROLLIZA' WHERE REPLACE(nombre, ' ', '') = 'COLUMNAENROLLIZAD=18CMSinanclaje(Ltipo=3,40mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN ROLLIZA' WHERE REPLACE(nombre, ' ', '') = 'COLUMNAENROLLIZAD=20CMSinanclaje(Ltipo=3,40mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'VIGAENGUADUAD=10CMIncluyeherrajes(Ltipo=3,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'VIGAENGUADUAD=12CMIncluyeherrajes(Ltipo=3,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'VIGAENGUADUAD=14CMIncluyeherrajes(Ltipo=3,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'VIGAENGUADUAD=16CMIncluyeherrajes(Ltipo=3,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'VIGAENGUADUAD=18CMIncluyeherrajes(Ltipo=3,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'DIAGONALENGUADUAD=10CMIncluyeherrajes(Ltipo=3,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'DIAGONALENGUADUAD=12CMIncluyeherrajes(Ltipo=3,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'DIAGONALENGUADUAD=14CMIncluyeherrajes(Ltipo=3,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'DIAGONALENGUADUAD=16CMIncluyeherrajes(Ltipo=3,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'DIAGONALENGUADUAD=18CMIncluyeherrajes(Ltipo=3,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'CORREAENGUADUAD=10CMIncluyeherrajes(Ltipo=2,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'CORREAENGUADUAD=12CMIncluyeherrajes(Ltipo=2,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'CORREAENGUADUAD=14CMIncluyeherrajes(Ltipo=2,00mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'CIELORASOENESTERILLA';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'CIELORASOENESTERILLAYMORTERO';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'MUROTENDINOSOENESTERILLA(Tipo4x3mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'MUROTENDINOSOENESTERILLA(Tipo3x3mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'MUROTENDINOSOENESTERILLA(Tipo2x3mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'MUROTENDINOSOMALLAC/VENA(Tipo4x3mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'MUROTENDINOSOMALLAC/VENA(Tipo3x3mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'MUROTENDINOSOMALLAC/VENA(Tipo2x3mt)';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'PISOENLATILLADEGUADUA';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'PISOENBALDOSADEGUADUA40X40';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'TABLEROENLATILLADEGUADUA';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'TABLEROENBALDOSADEGUADUA40X40';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'TINTILLASOBREGUADUAD=10CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'TINTILLASOBREGUADUAD=12CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'TINTILLASOBREGUADUAD=14CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'TINTILLASOBREGUADUAD=16CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'TINTILLASOBREGUADUAD=18CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'LINAZA/TREMENTINAGUADUAD=10CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'LINAZA/TREMENTINAGUADUAD=12CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'LINAZA/TREMENTINAGUADUAD=14CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'LINAZA/TREMENTINAGUADUAD=16CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'LINAZA/TREMENTINAGUADUAD=18CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'LACADEPOLIURETANODE2COMPONENTESS/GUADUAD=10CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'LACADEPOLIURETANODE2COMPONENTESS/GUADUAD=12CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'LACADEPOLIURETANODE2COMPONENTESS/GUADUAD=14CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'LACADEPOLIURETANODE2COMPONENTESS/GUADUAD=16CM';
UPDATE apu SET categoria_apu = 'CONSTRUCCION EN GUADUA' WHERE REPLACE(nombre, ' ', '') = 'LACADEPOLIURETANODE2COMPONENTESS/GUADUAD=18CM';
