-- AÑADIR CAMPO DE ESTADO PARA FLUJO DE APROBACIÓN
ALTER TABLE obra_avances ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'PENDIENTE';
ALTER TABLE control_asistencia ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'PENDIENTE';

-- COMENTARIOS DE DOCUMENTACIÓN
COMMENT ON COLUMN obra_avances.estado IS 'Estado del reporte: PENDIENTE, APROBADO, RECHAZADO';
COMMENT ON COLUMN control_asistencia.estado IS 'Estado del registro de asistencia: PENDIENTE, APROBADO, RECHAZADO';
